#!/bin/sh /etc/rc.common
#
# Copyright (c) 2014-2015 The Linux Foundation. All rights reserved.
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all copies.
#

START=80

have_cm() {
	[ -d "/sys/kernel/debug/ecm" ] && echo 1 && return

	echo 0
}

#load shortcut-fe connection manager
load_sfe_cm() {
	local kernel_version=$(uname -r)
	[ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && {
		[ -d /sys/module/fast_classifier ] || insmod /lib/modules/$kernel_version/fast-classifier.ko
	}
}

start() {
	[ "$(have_cm)" = "1" ] || load_sfe_cm
}

stop() {
	[ -d /sys/module/fast_classifier ] && rmmod fast_classifier
}
